[package]
name = "kaps"
version = "0.1.0"
edition = "2021"
authors = ["Polytech Montpellier - DevOps"]

[dependencies]
oci-image = { path = "oci-image" }
clap = { version = "3.0.5", features = ["derive"] }
container = { path = "container" }
oci-spec = "0.5.3"

[workspace]
members = [
        "container",
        "oci-image"
]